Keys = {
    ["ESC"] = 322, ["F1"] = 288, ["F2"] = 289, ["F3"] = 170, ["F5"] = 166, ["F6"] = 167, ["F7"] = 168, ["F8"] = 169, ["F9"] = 56, ["F10"] = 57,
    ["~"] = 243, ["1"] = 157, ["2"] = 158, ["3"] = 160, ["4"] = 164, ["5"] = 165, ["6"] = 159, ["7"] = 161, ["8"] = 162, ["9"] = 163, ["-"] = 84, ["="] = 83, ["BACKSPACE"] = 177,
    ["TAB"] = 37, ["Q"] = 44, ["W"] = 32, ["E"] = 38, ["R"] = 45, ["T"] = 245, ["Y"] = 246, ["U"] = 303, ["P"] = 199, ["["] = 39, ["]"] = 40, ["ENTER"] = 18,
    ["CAPS"] = 137, ["A"] = 34, ["S"] = 8, ["D"] = 9, ["F"] = 23, ["G"] = 47, ["H"] = 74, ["K"] = 311, ["L"] = 182,
    ["LEFTSHIFT"] = 21, ["Z"] = 20, ["X"] = 73, ["C"] = 26, ["V"] = 0, ["B"] = 29, ["N"] = 249, ["M"] = 244, [","] = 82, ["."] = 81,
    ["LEFTCTRL"] = 36, ["LEFTALT"] = 19, ["SPACE"] = 22, ["RIGHTCTRL"] = 70,
    ["HOME"] = 213, ["PAGEUP"] = 10, ["PAGEDOWN"] = 11, ["DELETE"] = 178,
    ["LEFT"] = 174, ["RIGHT"] = 175, ["TOP"] = 27, ["DOWN"] = 173,
}

Config = {}

Config.MenuItems = {
    {
        id = 'citizen',
        title = 'Fast menu',
        icon = 'user',
        items = {
            {
                id    = 'givenum',
                title = 'Copy phone number',
                icon = 'square-phone',
                type = 'client',
                event = 'esx_phone:CopyNumber',
                shouldClose = true,
            },
            {
                id    = 'nearplate',
                title = 'Copy near vehicle plate',
                icon = 'car',
                type = 'client',
                event = 'copynearplate',
                shouldClose = true,
            },
            {
                id    = 'HEX',
                title = 'Copy steam hex',
                icon = 'steam',
                type = 'client',
                event = 'copyhex',
                shouldClose = true,
            },
            {
                id    = 'house',
                title = 'Available houses blip',
                icon = 'house',
                type = 'client',
                event = 'togglehouseblip',
                shouldClose = true,
            },
            {
                id    = 'weaponserial',
                title = 'Copy current weapon serial',
                icon = 'gun',
                type = 'client',
                event = 'CopyCurrentWeaponSerial',
                shouldClose = true,
            },
            {
                id    = 'GunStyle',
                title = 'Change Holster Animation',
                icon = 'gun',
                type = 'client',
                event = 'openStyle',
                shouldClose = true,
            },
            {
                id    = 'creport',
                title = 'Report Player',
                icon = 'mask-face',
                type = 'client',
                event = 'esx_creport:OpenUI',
                shouldClose = true,
            },
        }
    },
    {
        id = 'gps',
        title = 'GPS Menu',
        icon = 'map-location',
        items = {
            {
                id    = 'sendalert',
                title = 'Send alert',
                icon = 'map-location-dot',
                type = 'client',
                event = 'radio:sendAlert',
                shouldClose = true,
            },
            {
                id    = 'sendalert',
                title = 'Show gps',
                icon = 'location-pin',
                type = 'client',
                event = 'radio:ShowGPS',
                shouldClose = true,
            },
        }
    },
    -- [2] = {
    --     id = 'general',
    --     title = 'General',
    --     icon = '#general',
    --     items = {
    --         {
    --             id = 'house',
    --             title = 'House Interactions',
    --             icon = '#house',
    --             items = {
    --                 {
    --                     id    = 'givehousekey',
    --                     title = 'Give house keys',
    --                     icon = '#vehiclekey',
    --                     type = 'client',
    --                     event = 'qb-houses:client:giveHouseKey',
    --                     shouldClose = true,
    --                     items = {},
    --                 },
    --                 {
    --                     id    = 'removehousekey',
    --                     title = 'Remove house keys',
    --                     icon = '#vehiclekey',
    --                     type = 'client',
    --                     event = 'qb-houses:client:removeHouseKey',
    --                     shouldClose = true,
    --                     items = {},
    --                 },
    --                 {
    --                     id    = 'togglelock',
    --                     title = 'Toggle lock',
    --                     icon = '#vehiclekey',
    --                     type = 'client',
    --                     event = 'qb-houses:client:toggleDoorlock',
    --                     shouldClose = true,
    --                 },
    --                 {
    --                     id    = 'decoratehouse',
    --                     title = 'Decorate house',
    --                     icon = '#vehiclekey',
    --                     type = 'client',
    --                     event = 'qb-houses:client:decorate',
    --                     shouldClose = true,
    --                 },            
    --                 {
    --                     id = 'houseLocations',
    --                     title = 'Interactions Locations',
    --                     icon = '#house',
    --                     items = {
    --                         {
    --                             id    = 'setstash',
    --                             title = 'Stash',
    --                             icon = '#vehiclekey',
    --                             type = 'client',
    --                             event = 'qb-houses:client:setLocation',
    --                             shouldClose = true,
    --                         },
    --                         {
    --                             id    = 'setoutift',
    --                             title = 'Outfit',
    --                             icon = '#vehiclekey',
    --                             type = 'client',
    --                             event = 'qb-houses:client:setLocation',
    --                             shouldClose = true,
    --                         },
    --                         {
    --                             id    = 'setlogout',
    --                             title = 'Logout',
    --                             icon = '#vehiclekey',
    --                             type = 'client',
    --                             event = 'qb-houses:client:setLocation',
    --                             shouldClose = true,
    --                         },
    --                     }
    --                 },
    --             }
    --         },
    --     }
    -- },
    -- [3] = {
    --     id = 'vehicle',
    --     title = 'Voertuig',
    --     icon = '#vehicle',
    --     items = {
    --         {
    --             id    = 'vehicledoors',
    --             title = 'Vehicle doors',
    --             icon = '#vehicledoors',
    --             items = {
    --                 {
    --                     id    = 'door0',
    --                     title = 'Front left',
    --                     icon = '#leftdoor',
    --                     type = 'client',
    --                     event = 'qb-radialmenu:client:openDoor',
    --                     shouldClose = false,
    --                 },
    --                 {
    --                     id    = 'door4',
    --                     title = 'Bonnet',
    --                     icon = '#idkaart',
    --                     type = 'client',
    --                     event = 'qb-radialmenu:client:openDoor',
    --                     shouldClose = false,
    --                 },
    --                 {
    --                     id    = 'door1',
    --                     title = 'Front right',
    --                     icon = '#rightdoor',
    --                     type = 'client',
    --                     event = 'qb-radialmenu:client:openDoor',
    --                     shouldClose = false,
    --                 },
    --                 {
    --                     id    = 'door3',
    --                     title = 'Right behind',
    --                     icon = '#rightdoor',
    --                     type = 'client',
    --                     event = 'qb-radialmenu:client:openDoor',
    --                     shouldClose = false,
    --                 },
    --                 {
    --                     id    = 'door5',
    --                     title = 'Trunk',
    --                     icon = '#idkaart',
    --                     type = 'client',
    --                     event = 'qb-radialmenu:client:openDoor',
    --                     shouldClose = false,
    --                 },
    --                 {
    --                     id    = 'door2',
    --                     title = 'Left behind',
    --                     icon = '#leftdoor',
    --                     type = 'client',
    --                     event = 'qb-radialmenu:client:openDoor',
    --                     shouldClose = false,
    --                 },
    --             }
    --         },
    --         {
    --             id    = 'vehicleextras',
    --             title = 'Vehicle Extras',
    --             icon = '#plus',
    --             items = {
    --                 {
    --                     id    = 'extra1',
    --                     title = 'Extra 1',
    --                     icon = '#plus',
    --                     type = 'client',
    --                     event = 'qb-radialmenu:client:setExtra',
    --                     shouldClose = false,
    --                 },
    --                 {
    --                     id    = 'extra2',
    --                     title = 'Extra 2',
    --                     icon = '#plus',
    --                     type = 'client',
    --                     event = 'qb-radialmenu:client:setExtra',
    --                     shouldClose = false,
    --                 },
    --                 {
    --                     id    = 'extra3',
    --                     title = 'Extra 3',
    --                     icon = '#plus',
    --                     type = 'client',
    --                     event = 'qb-radialmenu:client:setExtra',
    --                     shouldClose = false,
    --                 },
    --                 {
    --                     id    = 'extra4',
    --                     title = 'Extra 4',
    --                     icon = '#plus',
    --                     type = 'client',
    --                     event = 'qb-radialmenu:client:setExtra',
    --                     shouldClose = false,
    --                 },
    --                 {
    --                     id    = 'extra5',
    --                     title = 'Extra 5',
    --                     icon = '#plus',
    --                     type = 'client',
    --                     event = 'qb-radialmenu:client:setExtra',
    --                     shouldClose = false,
    --                 },
    --                 {
    --                     id    = 'extra6',
    --                     title = 'Extra 6',
    --                     icon = '#plus',
    --                     type = 'client',
    --                     event = 'qb-radialmenu:client:setExtra',
    --                     shouldClose = false,
    --                 },
    --                 {
    --                     id    = 'extra7',
    --                     title = 'Extra 7',
    --                     icon = '#plus',
    --                     type = 'client',
    --                     event = 'qb-radialmenu:client:setExtra',
    --                     shouldClose = false,
    --                 },
    --                 {
    --                     id    = 'extra8',
    --                     title = 'Extra 8',
    --                     icon = '#plus',
    --                     type = 'client',
    --                     event = 'qb-radialmenu:client:setExtra',
    --                     shouldClose = false,
    --                 },
    --                 {
    --                     id    = 'extra9',
    --                     title = 'Extra 9',
    --                     icon = '#plus',
    --                     type = 'client',
    --                     event = 'qb-radialmenu:client:setExtra',
    --                     shouldClose = false,
    --                 },                                                                                                                  
    --             }
    --         },
    --         {
    --             id    = 'vehicleseats',
    --             title = 'Vehicle seats',
    --             icon = '#vehicledoors',
    --             items = {
    --                 {
    --                     id    = 'door0',
    --                     title = 'Driver',
    --                     icon = '#plus',
    --                     type = 'client',
    --                     event = 'qb-radialmenu:client:ChangeSeat',
    --                     shouldClose = false,
    --                 },
    --             }
    --         },
    --     }
    -- },
    -- [4] = {
    --     id = 'jobinteractions',
    --     title = 'Jobs',
    --     icon = '#vehicle',
    --     items = {},
    -- },
}

-- Config.JobInteractions = {
--     ["doctor"] = {
--         {
--             id    = 'statuscheck',
--             title = 'Research Person',
--             icon = '#general',
--             type = 'client',
--             event = 'hospital:client:CheckStatus',
--             shouldClose = true,
--         },
--         {
--             id    = 'treatwounds',
--             title = 'Heal Wounds',
--             icon = '#general',
--             type = 'client',
--             event = 'hospital:client:TreatWounds',
--             shouldClose = true,
--         },
--         {
--             id    = 'reviveplayer',
--             title = 'Help Up',
--             icon = '#general',
--             type = 'client',
--             event = 'hospital:client:RevivePlayer',
--             shouldClose = true,
--         },
--         {
--             id    = 'emergencybutton2',
--             title = 'Emergency button',
--             icon = '#general',
--             type = 'client',
--             event = 'police:client:SendPoliceEmergencyAlert',
--             shouldClose = true,
--         },
--         {
--             id    = 'escort',
--             title = 'Escort',
--             icon = '#general',
--             type = 'client',
--             event = 'police:client:EscortPlayer',
--             shouldClose = true,
--         },
--         {
--             id = 'brancardoptions',
--             title = 'Stretcher',
--             icon = '#vehicle',
--             items = {
--                 {
--                     id    = 'spawnbrancard',
--                     title = 'Stretcher Spawn',
--                     icon = '#general',
--                     type = 'client',
--                     event = 'hospital:client:TakeBrancard',
--                     shouldClose = false,
--                 },
--                 {
--                     id    = 'despawnbrancard',
--                     title = 'Stretcher Despawn',
--                     icon = '#general',
--                     type = 'client',
--                     event = 'hospital:client:RemoveBrancard',
--                     shouldClose = false,
--                 },
--             },
--         },
--     },
--     ["ambulance"] = {
--         {
--             id    = 'statuscheck',
--             title = 'Research Person',
--             icon = '#general',
--             type = 'client',
--             event = 'hospital:client:CheckStatus',
--             shouldClose = true,
--         },
--         {
--             id    = 'treatwounds',
--             title = 'Heal wounds',
--             icon = '#general',
--             type = 'client',
--             event = 'hospital:client:TreatWounds',
--             shouldClose = true,
--         },
--         {
--             id    = 'emergencybutton2',
--             title = 'Emergency button',
--             icon = '#general',
--             type = 'client',
--             event = 'police:client:SendPoliceEmergencyAlert',
--             shouldClose = true,
--         },
--         {
--             id    = 'escort',
--             title = 'Escort',
--             icon = '#general',
--             type = 'client',
--             event = 'police:client:EscortPlayer',
--             shouldClose = true,
--         },
--         {
--             id = 'brancardoptions',
--             title = 'Stretcher',
--             icon = '#vehicle',
--             items = {
--                 {
--                     id    = 'spawnbrancard',
--                     title = 'Stretcher Spawn',
--                     icon = '#general',
--                     type = 'client',
--                     event = 'hospital:client:TakeBrancard',
--                     shouldClose = false,
--                 },
--                 {
--                     id    = 'despawnbrancard',
--                     title = 'Stretcher Despawn',
--                     icon = '#general',
--                     type = 'client',
--                     event = 'hospital:client:RemoveBrancard',
--                     shouldClose = false,
--                 },
--             },
--         },
--     },
--     ["taxi"] = {
--         {
--             id    = 'togglemeter',
--             title = 'Show/Hide Meter',
--             icon = '#general',
--             type = 'client',
--             event = 'qb-taxi:client:toggleMeter',
--             shouldClose = false,
--         },
--         {
--             id    = 'togglemouse',
--             title = 'Start/Stop Meter',
--             icon = '#general',
--             type = 'client',
--             event = 'qb-taxi:client:enableMeter',
--             shouldClose = true,
--         },
--         {
--             id    = 'npc_mission',
--             title = 'NPC Missions',
--             icon = '#general',
--             type = 'client',
--             event = 'qb-taxi:client:DoTaxiNpc',
--             shouldClose = true,
--         },
--     },
--     ["tow"] = {
--         {
--             id    = 'togglenpc',
--             title = 'Toggle NPC',
--             icon = '#general',
--             type = 'client',
--             event = 'jobs:client:ToggleNpc',
--             shouldClose = true,
--         },
--         {
--             id    = 'towvehicle',
--             title = 'Tow Vehicle',
--             icon = '#vehicle',
--             type = 'client',
--             event = 'qb-tow:client:TowVehicle',
--             shouldClose = true,
--         },
--     },
--     ["police"] = {
--         {
--             id    = 'emergencybutton',
--             title = 'Emergency button',
--             icon = '#general',
--             type = 'client',
--             event = 'police:client:SendPoliceEmergencyAlert',
--             shouldClose = true,
--         },
--         {
--             id    = 'checkvehstatus',
--             title = 'Check Tune Status',
--             icon = '#vehiclekey',
--             type = 'client',
--             event = 'qb-tunerchip:server:TuneStatus',
--             shouldClose = true,
--         },
--         {
--             id    = 'resethouse',
--             title = 'Reset Home lock',
--             icon = '#vehiclekey',
--             type = 'client',
--             event = 'qb-houses:client:ResetHouse',
--             shouldClose = true,
--         },
--         {
--             id    = 'takedriverlicense',
--             title = 'Take driver license',
--             icon = '#vehicle',
--             type = 'client',
--             event = 'police:client:SeizeDriverLicense',
--             shouldClose = true,
--         },
--         {
--             id = 'policeinteraction',
--             title = 'Police Interactions',
--             icon = '#house',
--             items = {
--                 {
--                     id    = 'statuscheck',
--                     title = 'Research Person',
--                     icon = '#general',
--                     type = 'client',
--                     event = 'hospital:client:CheckStatus',
--                     shouldClose = true,
--                 },
--                 {
--                     id    = 'checkstatus',
--                     title = 'Status Check',
--                     icon = '#general',
--                     type = 'client',
--                     event = 'police:client:CheckStatus',
--                     shouldClose = true,
--                 },
--                 {
--                     id    = 'escort',
--                     title = 'Escort',
--                     icon = '#general',
--                     type = 'client',
--                     event = 'police:client:EscortPlayer',
--                     shouldClose = true,
--                 },
--                 {
--                     id    = 'searchplayer',
--                     title = 'Search',
--                     icon = '#general',
--                     type = 'client',
--                     event = 'police:client:SearchPlayer',
--                     shouldClose = true,
--                 },
--                 {
--                     id    = 'jailplayer',
--                     title = 'Jail',
--                     icon = '#general',
--                     type = 'client',
--                     event = 'police:client:JailPlayer',
--                     shouldClose = true,
--                 },
--             }
--         },
--         {
--             id = 'policeobjects',
--             title = 'Objects',
--             icon = '#house',
--             items = {
--                 {
--                     id    = 'spawnpion',
--                     title = 'Pion',
--                     icon = '#vehiclekey',
--                     type = 'client',
--                     event = 'police:client:spawnCone',
--                     shouldClose = false,
--                 },
--                 {
--                     id    = 'spawnhek',
--                     title = 'Hek',
--                     icon = '#vehiclekey',
--                     type = 'client',
--                     event = 'police:client:spawnBarier',
--                     shouldClose = false,
--                 },
--                 {
--                     id    = 'spawnschotten',
--                     title = 'Barier',
--                     icon = '#vehiclekey',
--                     type = 'client',
--                     event = 'police:client:spawnSchotten',
--                     shouldClose = false,
--                 },
--                 {
--                     id    = 'spawntent',
--                     title = 'Tent',
--                     icon = '#vehiclekey',
--                     type = 'client',
--                     event = 'police:client:spawnTent',
--                     shouldClose = false,
--                 },
--                 {
--                     id    = 'spawnverlichting',
--                     title = 'Lighting',
--                     icon = '#vehiclekey',
--                     type = 'client',
--                     event = 'police:client:spawnLight',
--                     shouldClose = false,
--                 },
--                 {
--                     id    = 'spikestrip',
--                     title = 'Spikestrip',
--                     icon = '#vehiclekey',
--                     type = 'client',
--                     event = 'police:client:SpawnSpikeStrip',
--                     shouldClose = false,
--                 },
--                 {
--                     id    = 'deleteobject',
--                     title = 'Object Deleter',
--                     icon = '#vehiclekey',
--                     type = 'client',
--                     event = 'police:client:deleteObject',
--                     shouldClose = false,
--                 },
--             }
--         },
--     },
--     ["hotdog"] = {
--         {
--             id    = 'togglesell',
--             title = 'Toggle sell',
--             icon = '#general',
--             type = 'client',
--             event = 'qb-hotdogjob:client:ToggleSell',
--             shouldClose = true,
--         },
--     },
--     -- ["taxi"] = {

--     -- },
-- }
