---@diagnostic disable: undefined-field
ConfigPilot = {}
    
ConfigPilot.ComehereModDriveStyle = 262701 -- Driving style for comehere command
ConfigPilot.ComehereModSpeed = 40.0 -- Speed for comehere command

ConfigPilot.UseKmh = "kmh" -- "kmh" or "mph"

-- Emergency mode active location
ConfigPilot.EmergencyLocation = {x = 298.0, y = -584.0, z = 43.3}
-- Emergency mode driving style
ConfigPilot.EmergencyDrivingStyle = 262692

-- Vehicles with autopilot activated
ConfigPilot.Vehicles = { 
    [`hrculimo`] = true,
    [`ikx3rezvani`] = true,
    [`amirpeju`]= true,
    [`minirocketman`] = true,
    [`maclaren_mp4`] = true,
    [`chargerf8`] = true,
    [`fxxk`] = true,
    [`mbc`] = true,
    [`benzb50`] = true,
    [`tlc300`] = true,
    [`zlay_gtrkuhlc `]= true,
    [`gcmmbgls600`] = true,
    [`nm_avent`] = true,
    [`pd_avent2`] = true,
    [`onebeast`] = true,
    [`teslapd`] = true,
    [`royzhoxtor`] = true,
    [`faketaxih`] = true,
    [`urusvennum`] = true,
    [`a80`]= true,
    [`taxi2`] = true,
    [`fh500`] = true,
    [`500w124`] = true,
    [`charge4`] = true,
    [`oycmr500`] = true,
    [`rmodatlantic`]= true,
    [`sspres`] = true,
    [`undercls`] = true,
    [`yaiba`] = true,
    [`REGALIA`] = true,
    [`larryuni`] = true,
    [`206pr`] = true,
    [`aperta`] = true,
}

-- Fixed locations for LiveMap
ConfigPilot.FixedLocations = {
    PoliceStation = { -- fixed Location name
        coords = {x = 438.59, y = -982.33, z = 30.69}, -- fixed location coords
        icon = "directions/fixedlocations", -- fixed location icon
    },
    Hospital = {
        coords = {x = -678.12, y = 300.21, z = 82.15},
        icon = "directions/fixedlocations",
    },
    Justice = {
        coords ={x = -530.64, y = -228.26, z = 36.71},
        icon = "directions/fixedlocations",
    },
    MCentral = {
        coords = { x = -354.88, y = -125.21, z = 39.43},
        icon = "directions/fixedlocations",
    },
    MCbenny = {
        coords = { x = -527.97, y = -1777.06, z = 21.37},
        icon = "directions/fixedlocations",
    },
    Sheriff = {
        coords = { x = 1866.3, y = 3674.22, z = 33.8},
        icon = "directions/fixedlocations",
    },
    MDsandy = {
        coords = { x = 1775.35, y = 3631.85, z = 34.69},
        icon = "directions/fixedlocations",
    },
}

ConfigPilot.Keys = {
    ["E"] = 38, -- Using Park Section, Submit Park Position
    ["H"] = 74, -- Using Park Section, Cancel Parking
    ["LEFT_ARROW"] = 174, -- Using Park Section
    ["RIGHT_ARROW"] = 175, -- Using Park Section
    ["K"] = 311,    -- Open Cursor in Autopilot screen
    ["U"] = 303,    -- Cancel Trip hotkey
}
--autopilot speed multiplier
ConfigPilot.speedMultiplier = { 
    ["ecomode"] = 40.0,
    ["sportmode"] = 90.0,
    ["sportPlus"] = 150.0,
    ["emergency"] = 70.0,
}

--Notify Texts
ConfigPilot.Texts = {
    parkingPilot = "Parking Pilot Activated.",
    parkingPilot_stop = "Parking Pilot Stoped.",
    autoPilot_start = "AutoPilot %s Activated.",
    autoPilot_stop = "AutoPilot %s Stoped.",
    reach_destination = "We've reached our destination.",
    vehicle_came_to_you = "%s arrived to you",
    not_in_vehicle = "You are not in vehicle",
    cant_come = "We've lost contact with your vehicle",
    autoPilot_not_active = "%s is not active",
    driver_in_vehicle = "Driver is in vehicle",
    stopped_dancing = " %s Stopped dancing",
    started_dancing = " %s Started dancing",
    otopilot_active_cant_park = "AutoPilot is active, you can't park",
}

--ConfigPiloturable Notify Function, you can edit your notify system
function Notify(text, type, time)
    ESX.ShowNotification(text)
end

-- ConfigPiloturable street speed limit sign
ConfigPilot.SpeedLimits = {
    ["East Joshua Road"] = "50",
    ["Marina Dr"] = "35",
    ["Alhambra Dr"] = "35",
    ["Niland Ave"] = "35",
    ["Zancudo Ave"] = "35",
    ["Armadillo Ave"] = "35",
    ["Algonquin Blvd"] = "35",
    ["Mountain View Dr"] = "35",
    ["Cholla Springs Ave"] = "35",
    ["Panorama Dr"] = "40",
    ["Lesbos Ln"] = "35",
    ["Calafia Rd"] = "30",
    ["North Calafia Way"] = "30",
    ["Cassidy Trail"] = "25",
    ["Seaview Rd"] = "35",
    ["Grapeseed Main St"] = "35",
    ["Grapeseed Ave"] = "35",
    ["Joad Ln"] = "35",
    ["Union Rd"] = "40",
    ["O'Neil Way"] = "25",
    ["Senora Fwy"] = "65",
    ["Catfish View"] = "35",
    ["Great Ocean Hwy"] = "60",
    ["Paleto Blvd"] = "35",
    ["Duluoz Ave"] = "35",
    ["Procopio Dr"] = "35",
    ["Cascabel Ave"] = "30",
    ["Procopio Promenade"] = "25",
    ["Pyrite Ave"] = "30",
    ["Fort Zancudo Approach Rd"] = "25",
    ["Barbareno Rd"] = "30",
    ["Ineseno Road"] = "30",
    ["West Eclipse Blvd"] = "35",
    ["Playa Vista"] = "30",
    ["Bay City Ave"] = "30",
    ["Del Perro Fwy"] = "65",
    ["Equality Way"] = "30",
    ["Red Desert Ave"] = "30",
    ["Magellan Ave"] = "25",
    ["Sandcastle Way"] = "30",
    ["Vespucci Blvd"] = "40",
    ["Prosperity St"] = "30",
    ["San Andreas Ave"] = "40",
    ["North Rockford Dr"] = "35",
    ["South Rockford Dr"] = "35",
    ["Marathon Ave"] = "30",
    ["Boulevard Del Perro"] = "35",
    ["Cougar Ave"] = "30",
    ["Liberty St"] = "30",
    ["Bay City Incline"] = "40",
    ["Conquistador St"] = "25",
    ["Cortes St"] = "25",
    ["Vitus St"] = "25",
    ["Aguja St"] = "25",
    ["Goma St"] = "25",
    ["Melanoma St"] = "25",
    ["Palomino Ave"] = "35",
    ["Invention Ct"] = "25",
    ["Imagination Ct"] = "25",
    ["Rub St"] = "25",
    ["Tug St"] = "25",
    ["Ginger St"] = "30",
    ["Lindsay Circus"] = "30",
    ["Calais Ave"] = "35",
    ["Adam's Apple Blvd"] = "40",
    ["Alta St"] = "40",
    ["Integrity Way"] = "30",
    ["Swiss St"] = "30",
    ["Strawberry Ave"] = "40",
    ["Capital Blvd"] = "30",
    ["Crusade Rd"] = "30",
    ["Innocence Blvd"] = "40",
    ["Davis Ave"] = "40",
    ["Little Bighorn Ave"] = "35",
    ["Roy Lowenstein Blvd"] = "35",
    ["Jamestown St"] = "30",
    ["Carson Ave"] = "35",
    ["Grove St"] = "30",
    ["Brouge Ave"] = "30",
    ["Covenant Ave"] = "30",
    ["Dutch London St"] = "40",
    ["Signal St"] = "30",
    ["Elysian Fields Fwy"] = "50",
    ["Plaice Pl"] = "30",
    ["Chum St"] = "40",
    ["Chupacabra St"] = "30",
    ["Miriam Turner Overpass"] = "30",
    ["Autopia Pkwy"] = "35",
    ["Exceptionalists Way"] = "35",
    ["La Puerta Fwy"] = "60",
    ["New Empire Way"] = "30",
    ["Runway1"] = "",
    ["Greenwich Pkwy"] = "35",
    ["Kortz Dr"] = "30",
    ["Banham Canyon Dr"] = "40",
    ["Buen Vino Rd"] = "40",
    ["Route 68"] = "55",
    ["Zancudo Grande Valley"] = "40",
    ["Zancudo Barranca"] = "40",
    ["Galileo Rd"] = "40",
    ["Mt Vinewood Dr"] = "40",
    ["Marlowe Dr"] = "40",
    ["Milton Rd"] = "35",
    ["Kimble Hill Dr"] = "35",
    ["Normandy Dr"] = "35",
    ["Hillcrest Ave"] = "35",
    ["Hillcrest Ridge Access Rd"] = "35",
    ["North Sheldon Ave"] = "35",
    ["Lake Vinewood Dr"] = "35",
    ["Lake Vinewood Est"] = "35",
    ["Baytree Canyon Rd"] = "40",
    ["North Conker Ave"] = "35",
    ["Wild Oats Dr"] = "35",
    ["Whispymound Dr"] = "35",
    ["Didion Dr"] = "35",
    ["Cox Way"] = "35",
    ["Picture Perfect Drive"] = "35",
    ["South Mo Milton Dr"] = "35",
    ["Cockingend Dr"] = "35",
    ["Mad Wayne Thunder Dr"] = "35",
    ["Hangman Ave"] = "35",
    ["Dunstable Ln"] = "35",
    ["Dunstable Dr"] = "35",
    ["Greenwich Way"] = "35",
    ["Greenwich Pl"] = "35",
    ["Hardy Way"] = "35",
    ["Richman St"] = "35",
    ["Ace Jones Dr"] = "35",
    ["Los Santos Freeway"] = "65",
    ["Senora Rd"] = "40",
    ["Nowhere Rd"] = "25",
    ["Smoke Tree Rd"] = "35",
    ["Cholla Rd"] = "35",
    ["Cat-Claw Ave"] = "35",
    ["Senora Way"] = "40",
    ["Palomino Fwy"] = "60",
    ["Shank St"] = "25",
    ["Macdonald St"] = "35",
    ["Route 68 Approach"] = "55",
    ["Vinewood Park Dr"] = "35",
    ["Vinewood Blvd"] = "40",
    ["Mirror Park Blvd"] = "35",
    ["Glory Way"] = "35",
    ["Bridge St"] = "35",
    ["West Mirror Drive"] = "35",
    ["Nikola Ave"] = "35",
    ["East Mirror Dr"] = "35",
    ["Nikola Pl"] = "25",
    ["Mirror Pl"] = "35",
    ["El Rancho Blvd"] = "40",
    ["Olympic Fwy"] = "60",
    ["Fudge Ln"] = "25",
    ["Amarillo Vista"] = "25",
    ["Labor Pl"] = "35",
    ["El Burro Blvd"] = "35",
    ["Sustancia Rd"] = "45",
    ["South Shambles St"] = "30",
    ["Hanger Way"] = "30",
    ["Orchardville Ave"] = "30",
    ["Popular St"] = "40",
    ["Buccaneer Way"] = "45",
    ["Abattoir Ave"] = "35",
    ["Voodoo Place"] = "30",
    ["Mutiny Rd"] = "35",
    ["South Arsenal St"] = "35",
    ["Forum Dr"] = "35",
    ["Morningwood Blvd"] = "35",
    ["Dorset Dr"] = "40",
    ["Caesars Place"] = "25",
    ["Spanish Ave"] = "30",
    ["Portola Dr"] = "30",
    ["Edwood Way"] = "25",
    ["San Vitus Blvd"] = "40",
    ["Eclipse Blvd"] = "35",
    ["Gentry Lane"] = "30",
    ["Las Lagunas Blvd"] = "40",
    ["Power St"] = "40",
    ["Mt Haan Rd"] = "40",
    ["Elgin Ave"] = "40",
    ["Hawick Ave"] = "35",
    ["Meteor St"] = "30",
    ["Alta Pl"] = "30",
    ["Occupation Ave"] = "35",
    ["Carcer Way"] = "40",
    ["Eastbourne Way"] = "30",
    ["Rockford Dr"] = "35",
    ["Abe Milton Pkwy"] = "35",
    ["Laguna Pl"] = "30",
    ["Sinners Passage"] = "30",
    ["Atlee St"] = "30",
    ["Sinner St"] = "30",
    ["Supply St"] = "30",
    ["Amarillo Way"] = "35",
    ["Tower Way"] = "35",
    ["Decker St"] = "35",
    ["Tackle St"] = "25",
    ["Low Power St"] = "35",
    ["Clinton Ave"] = "35",
    ["Fenwell Pl"] = "35",
    ["Utopia Gardens"] = "25",
    ["Cavalry Blvd"] = "35",
    ["South Boulevard Del Perro"] = "35",
    ["Americano Way"] = "25",
    ["Sam Austin Dr"] = "25",
    ["East Galileo Ave"] = "35",
    ["Galileo Park"] = "35",
    ["West Galileo Ave"] = "35",
    ["Tongva Dr"] = "40",
    ["Zancudo Rd"] = "35",
    ["Movie Star Way"] = "35",
    ["Heritage Way"] = "35",
    ["Perth St"] = "25",
    ["Chianski Passage"] = "30",
    ["Lolita Ave"] = "35",
    ["Meringue Ln"] = "35",
    ["Joshua Rd"] = "50"
}
