Config = {}
Config.PunishPlayerPermission = 4
Config.UnminifyPunish = {
	["DM"] = "Death Match",
    ["VDM"] = "Vehicle Death Match",
    ["NCZ"] = "No Crime Zone/Safe Zone",
    ["MIO"] = "Mix IC OOC",
    ["MGJ"] = "Meta Gaming (Major)",
    ["RNP"] = "Naghze Ghavanin New Players",
    ["RRD"] = "Robbery Rules (Bank, Shop ...)",
    ["RRC"] = "Kheftgiri (Serghat)",
    ["FRP"] = "Fear RP",
    ["CB"] = "Cop Baiting",
    ["PG"] = "Power Gaming",
    ["NLR"] = "New Life Rule",
    ["HR"] = "Hostage Rule",
    ["CL"] = "Combat Logging",
	["SEARCH"] = "Naghz Ghavanine Search",
    ["STRP"] = "Sexual/Torture RP",
    ["MCA"] = "Mic Abuse",
    ["HARAS"] = "Harassment",
    ["OI"] = "OOC Insult",
    ["ITS"] = "Insult To Staff",
	["FN"] = "Fahashi Namosi",
	["MGH"] = "Morore Ghavanin",
	["TR"] = "Trash Report",
	["MRC"] = "Mercy Killing",
	["EA"] = "Emote Abuse",
	["JAF"] = "Job Abuse (Factions)",
	["JAM"] = "Job Abuse (Military)",
	["NRPP"] = "Naghz RP Pause",
	["CHEAT"] = "Cheat",
	["GLITCH"] = 'Bug Abuse',
    ["TBGH"] = "Tabligh",
	["RDM"] = "Random DM",
	["TRP"] = "Troll RP",
	["K.O.S"] = "Kill On Sight(KOS)",
	["BRP"] = "Block RP",
}

Config["K.O.S"] = {
	{
		resoan = 'Offence 1',
		jail_Time = nil,
		cs_count = 30,
		ban_time = nil,
		fine_amount = 50000,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = 60,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = nil,
		cs_count = 80,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = 200,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
}

Config.DM = {
	{
		resoan = 'Offence 1',
		jail_Time = nil,
		cs_count = 60,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = 80,
		ban_time = nil,
		fine_amount = 50000,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = nil,
		cs_count = 120,
		ban_time = nil,
		fine_amount = 200000,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = 200,
		ban_time = 1,
		fine_amount = 300000,
		kick = nil,
	},
	{
		resoan = 'Offence 5',
		jail_Time = nil,
		cs_count = 250,
		ban_time = nil,
		fine_amount = 500000,
		kick = nil,
	},
	{
		resoan = 'Offence 6',
		jail_Time = nil,
		cs_count = 300,
		ban_time = nil,
		fine_amount = 600000,
		kick = nil,
	},
	{
		resoan = 'Offence 7',
		jail_Time = nil,
		cs_count = 400,
		ban_time = 3,
		fine_amount = 800000,
		kick = nil,
	},

}

Config.VDM = {
	{
		resoan = 'Offence 1',
		jail_Time = 30,
		cs_count = nil,
		ban_time = nil,
		fine_amount = 50000,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = 60,
		ban_time = nil,
		fine_amount = 100000,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = nil,
		cs_count = 80,
		ban_time = nil,
		fine_amount = 200000,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = 120,
		ban_time = 1,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 5',
		jail_Time = nil,
		cs_count = 250,
		ban_time = nil,
		fine_amount = 400000,
		kick = nil,
	},
	{
		resoan = 'Offence 6',
		jail_Time = nil,
		cs_count = 300,
		ban_time = nil,
		fine_amount = 600000,
		kick = nil,
	},
	{
		resoan = 'Offence 7',
		jail_Time = nil,
		cs_count = 400,
		ban_time = nil,
		fine_amount = 800000,
		kick = nil,
	},

}

Config.NCZ = {
	{
		resoan = 'Warn',
		jail_Time = nil,
		cs_count = nil,
		ban_time = nil,
		fine_amount = 50000,
		kick = nil,
	},
	{
		resoan = 'Offence 1',
		jail_Time = 40,
		cs_count = nil,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = 60,
		ban_time = nil,
		fine_amount = 50000,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = nil,
		cs_count = 120,
		ban_time = nil,
		fine_amount = 200000,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = 200,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 5',
		jail_Time = nil,
		cs_count = 200,
		ban_time = 1,
		fine_amount = 300000,
		kick = nil,
	},
	{
		resoan = 'Offence 6',
		jail_Time = nil,
		cs_count = 300,
		ban_time = nil,
		fine_amount = 500000,
		kick = nil,
	},
	{
		resoan = 'Offence 7',
		jail_Time = nil,
		cs_count = 500,
		ban_time = nil,
		fine_amount = 800000,
		kick = nil,
	},

}

Config.MIO = {
	{
		resoan = 'Warn',
		jail_Time = nil,
		cs_count = nil,
		ban_time = nil,
		fine_amount = 20000,
		kick = nil,
	},
	{
		resoan = 'Offence 1',
		jail_Time = 30,
		cs_count = nil,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = 40,
		ban_time = nil,
		fine_amount = 100000,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = nil,
		cs_count = 60,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = 80,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 5',
		jail_Time = nil,
		cs_count = 120,
		ban_time = 1,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 6',
		jail_Time = nil,
		cs_count = 200,
		ban_time = nil,
		fine_amount = 500000,
		kick = nil,
	},
	{
		resoan = 'Offence 7',
		jail_Time = nil,
		cs_count = 300,
		ban_time = nil,
		fine_amount = 800000,
		kick = nil,
	},

}

Config.MGJ = {
	{
		resoan = 'Offence 1',
		jail_Time = 40,
		cs_count = nil,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = 60,
		ban_time = nil,
		fine_amount = 100000,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = nil,
		cs_count = 80,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = 120,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 5',
		jail_Time = nil,
		cs_count = 200,
		ban_time = 1,
		fine_amount = 300000,
		kick = nil,
	},
	{
		resoan = 'Offence 6',
		jail_Time = nil,
		cs_count = 300,
		ban_time = nil,
		fine_amount = 1000000,
		kick = nil,
	},
	{
		resoan = 'Offence 7',
		jail_Time = nil,
		cs_count = 400,
		ban_time = nil,
		fine_amount = 1000000,
		kick = nil,
	},

}

Config.RNP = {
	{
		resoan = 'Offence 1',
		jail_Time = 20,
		cs_count = nil,
		ban_time = nil,
		fine_amount = 10000,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = 40,
		ban_time = nil,
		fine_amount = 50000,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = nil,
		cs_count = 60,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = 80,
		ban_time = 1,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 5',
		jail_Time = nil,
		cs_count = 200,
		ban_time = nil,
		fine_amount = 300000,
		kick = nil,
	},
	{
		resoan = 'Offence 6',
		jail_Time = nil,
		cs_count = 250,
		ban_time = nil,
		fine_amount = 500000,
		kick = nil,
	},

}

Config.RRD = {
	{
		resoan = 'Offence 1',
		jail_Time = nil,
		cs_count = 40,
		ban_time = nil,
		fine_amount = 40000,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = 60,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = nil,
		cs_count = 120,
		ban_time = nil,
		fine_amount = 150000,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = 200,
		ban_time = 1,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 5',
		jail_Time = nil,
		cs_count = 250,
		ban_time = nil,
		fine_amount = 400000,
		kick = nil,
	},
	{
		resoan = 'Offence 6',
		jail_Time = nil,
		cs_count = 300,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 7',
		jail_Time = nil,
		cs_count = 400,
		ban_time = nil,
		fine_amount = 1000000,
		kick = nil,
	},

}

Config.RRC = {
	{
		resoan = 'Offence 1',
		jail_Time = 30,
		cs_count = nil,
		ban_time = nil,
		fine_amount = 40000,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = 60,
		ban_time = nil,
		fine_amount = 100000,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = nil,
		cs_count = 80,
		ban_time = nil,
		fine_amount = 150000,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = 120,
		ban_time = 1,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 5',
		jail_Time = nil,
		cs_count = 200,
		ban_time = nil,
		fine_amount = 500000,
		kick = nil,
	},
	{
		resoan = 'Offence 6',
		jail_Time = nil,
		cs_count = 300,
		ban_time = nil,
		fine_amount = 800000,
		kick = nil,
	},

}

Config.FRP = {
	{
		resoan = 'Offence 1',
		jail_Time = 30,
		cs_count = nil,
		ban_time = nil,
		fine_amount = 80000,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = 60,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = nil,
		cs_count = 80,
		ban_time = nil,
		fine_amount = 200000,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = 120,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 5',
		jail_Time = nil,
		cs_count = 200,
		ban_time = 1,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 6',
		jail_Time = nil,
		cs_count = 300,
		ban_time = nil,
		fine_amount = 400000,
		kick = nil,
	},

}

Config.CB = {
	{
		resoan = 'Warn',
		jail_Time = nil,
		cs_count = nil,
		ban_time = nil,
		fine_amount = 50000,
		kick = nil,
	},
	{
		resoan = 'Offence 1',
		jail_Time = nil,
		cs_count = 60,
		ban_time = nil,
		fine_amount = 50000,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = 80,
		ban_time = nil,
		fine_amount = 100000,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = nil,
		cs_count = 120,
		ban_time = nil,
		fine_amount = 50000,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = 200,
		ban_time = 1,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 5',
		jail_Time = nil,
		cs_count = 250,
		ban_time = 3,
		fine_amount = nil,
		kick = nil,
	},

}

Config.PG = {
	{
		resoan = 'Warn',
		jail_Time = nil,
		cs_count = nil,
		ban_time = nil,
		fine_amount = 50000,
		kick = nil,
	},
	{
		resoan = 'Offence 1',
		jail_Time = 30,
		cs_count = nil,
		ban_time = nil,
		fine_amount = 50000,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = 60,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = nil,
		cs_count = 80,
		ban_time = nil,
		fine_amount = 250000,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = 120,
		ban_time = 1,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 5',
		jail_Time = nil,
		cs_count = 200,
		ban_time = 3,
		fine_amount = nil,
		kick = nil,
	},

}

Config.NLR = {
	{
		resoan = 'Offence 1',
		jail_Time = 30,
		cs_count = nil,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = 60,
		ban_time = nil,
		fine_amount = 300000,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = nil,
		cs_count = 80,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = 120,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 5',
		jail_Time = nil,
		cs_count = 200,
		ban_time = 1,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 6',
		jail_Time = nil,
		cs_count = 400,
		ban_time = nil,
		fine_amount = 250000,
		kick = nil,
	},
	{
		resoan = 'Offence 7',
		jail_Time = nil,
		cs_count = 500,
		ban_time = nil,
		fine_amount = 400000,
		kick = nil,
	},

}

Config.HR = {
	{
		resoan = 'Offence 1',
		jail_Time = 30,
		cs_count = nil,
		ban_time = nil,
		fine_amount = 50000,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = 60,
		ban_time = nil,
		fine_amount = 200000,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = nil,
		cs_count = 80,
		ban_time = nil,
		fine_amount = 200000,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = 120,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 5',
		jail_Time = nil,
		cs_count = 200,
		ban_time = 1,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 6',
		jail_Time = nil,
		cs_count = 250,
		ban_time = nil,
		fine_amount = 400000,
		kick = nil,
	},
	{
		resoan = 'Offence 7',
		jail_Time = nil,
		cs_count = 300,
		ban_time = nil,
		fine_amount = 1000000,
		kick = nil,
	},

}

Config.CL = {
	{
		resoan = 'Offence 1',
		jail_Time = nil,
		cs_count = 80,
		ban_time = nil,
		fine_amount = 50000,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = 120,
		ban_time = nil,
		fine_amount = 100000,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = nil,
		cs_count = 200,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = 250,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 5',
		jail_Time = nil,
		cs_count = 400,
		ban_time = 2,
		fine_amount = 250000,
		kick = nil,
	},
}

Config.STRP = {
	{
		resoan = 'Offence 1',
		jail_Time = nil,
		cs_count = 80,
		ban_time = nil,
		fine_amount = 100000,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = 120,
		ban_time = nil,
		fine_amount = 100000,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = nil,
		cs_count = 200,
		ban_time = 1,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = 300,
		ban_time = 4,
		fine_amount = 1000000,
		kick = nil,
	},
}

Config.MCA = {
	{
		resoan = 'Warn',
		jail_Time = nil,
		cs_count = nil,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 1',
		jail_Time = 40,
		cs_count = nil,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = 80,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = nil,
		cs_count = 120,
		ban_time = nil,
		fine_amount = 100000,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = 200,
		ban_time = 1,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 5',
		jail_Time = nil,
		cs_count = 300,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},

}

Config.HARAS = {
	{
		resoan = 'Warn',
		jail_Time = nil,
		cs_count = nil,
		ban_time = nil,
		fine_amount = 100000,
		kick = nil,
	},
	{
		resoan = 'Offence 1',
		jail_Time = nil,
		cs_count = 80,
		ban_time = nil,
		fine_amount = 200000,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = 120,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = nil,
		cs_count = 200,
		ban_time = 3,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = 250,
		ban_time = nil,
		fine_amount = 300000,
		kick = nil,
	},
	{
		resoan = 'Offence 5',
		jail_Time = nil,
		cs_count = 400,
		ban_time = 7,
		fine_amount = 1000000,
		kick = nil,
	},
	

}

Config.OI = {
	{
		resoan = 'Offence 1',
		jail_Time = 40,
		cs_count = nil,
		ban_time = nil,
		fine_amount = 50000,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = 120,
		ban_time = nil,
		fine_amount = 100000,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = nil,
		cs_count = 200,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = 250,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 5',
		jail_Time = nil,
		cs_count = 300,
		ban_time = 2,
		fine_amount = 500000,
		kick = nil,
	},
	{
		resoan = 'Offence 6',
		jail_Time = nil,
		cs_count = 400,
		ban_time = nil,
		fine_amount = 500000,
		kick = nil,
	},
}

Config.ITS = {
	{
		resoan = 'Offence 1',
		jail_Time = nil,
		cs_count = nil,
		ban_time = 2,
		fine_amount = 400000,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = nil,
		ban_time = -1,
		fine_amount = nil,
		kick = nil,
	},
}

Config.CHEAT = {
	{
		resoan = 'Offence 1',
		jail_Time = nil,
		cs_count = nil,
		ban_time = -1,
		fine_amount = nil,
		kick = nil,
	},
}

Config.GLITCH = {
	{
		resoan = 'Offence 1',
		jail_Time = nil,
		cs_count = 250,
		ban_time = 10,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = nil,
		ban_time = -1,
		fine_amount = nil,
		kick = nil,
	},
}

Config.MGH = {
	{
		resoan = 'Offence 1',
		jail_Time = 30,
		cs_count = nil,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	}
}

Config.TBGH = {
	{
		resoan = 'Offence 1',
		jail_Time = nil,
		cs_count = nil,
		ban_time = -1,
		fine_amount = nil,
		kick = nil,
	},
}

Config.TR = {
	{
		resoan = 'Warn',
		jail_Time = nil,
		cs_count = nil,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 1',
		jail_Time = nil,
		cs_count = nil,
		ban_time = nil,
		fine_amount = 100000,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = 30,
		cs_count = nil,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = 60,
		cs_count = nil,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = 100,
		ban_time = nil,
		fine_amount = 150000,
		kick = nil,
	},
	{
		resoan = 'Offence 5',
		jail_Time = nil,
		cs_count = 250,
		ban_time = nil,
		fine_amount = 250000,
		kick = nil,
	},
}

Config.MRC = {
	{
		resoan = 'Warn',
		jail_Time = nil,
		cs_count = nil,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 1',
		jail_Time = 40,
		cs_count = nil,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = 80,
		ban_time = nil,
		fine_amount = 100000,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = nil,
		cs_count = 120,
		ban_time = nil,
		fine_amount = 200000,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = 200,
		ban_time = 1,
		fine_amount = 150000,
		kick = nil,
	},
	{
		resoan = 'Offence 5',
		jail_Time = nil,
		cs_count = 500,
		ban_time = nil,
		fine_amount = 1000000,
		kick = nil,
	},

}

Config.EA = {
	{
		resoan = 'Offence 1',
		jail_Time = 40,
		cs_count = nil,
		ban_time = nil,
		fine_amount = 50000,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = 80,
		ban_time = nil,
		fine_amount = 100000,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = nil,
		cs_count = 120,
		ban_time = nil,
		fine_amount = 50000,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = 200,
		ban_time = nil,
		fine_amount = 150000,
		kick = nil,
	},
	{
		resoan = 'Offence 5',
		jail_Time = nil,
		cs_count = 250,
		ban_time = 1,
		fine_amount = 500000,
		kick = nil,
	},
	{
		resoan = 'Offence 6',
		jail_Time = nil,
		cs_count = 400,
		ban_time = 5,
		fine_amount = 1000000,
		kick = nil,
	},

}

Config.JAF = {
	{
		resoan = 'Offence 1',
		jail_Time = nil,
		cs_count = 80,
		ban_time = nil,
		fine_amount = 100000,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = 120,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = nil,
		cs_count = 200,
		ban_time = nil,
		fine_amount = 250000,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = 250,
		ban_time = 1,
		fine_amount = 300000,
		kick = nil,
	},
	{
		resoan = 'Offence 5',
		jail_Time = nil,
		cs_count = 400,
		ban_time = 3,
		fine_amount = 500000,
		kick = nil,
	},

}

Config.JAM = {
	{
		resoan = 'Offence 1',
		jail_Time = nil,
		cs_count = 200,
		ban_time = nil,
		fine_amount = 200000,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = 250,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = nil,
		cs_count = 400,
		ban_time = nil,
		fine_amount = 500000,
		kick = nil,
	},

}

Config.NRPP = {
	{
		resoan = 'Offence 1',
		jail_Time = 30,
		cs_count = nil,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = 45,
		cs_count = nil,
		ban_time = nil,
		fine_amount = 50000,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = nil,
		cs_count = 80,
		ban_time = nil,
		fine_amount = 100000,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = 120,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 5',
		jail_Time = nil,
		cs_count = 200,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 6',
		jail_Time = nil,
		cs_count = 250,
		ban_time = 1,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 7',
		jail_Time = nil,
		cs_count = 400,
		ban_time = nil,
		fine_amount = 1000000,
		kick = nil,
	},

}

Config.FN = {
	{
		resoan = 'Offence 1',
		jail_Time = nil,
		cs_count = 250,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = 350,
		ban_time = 3,
		fine_amount = 200000,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = nil,
		cs_count = 400,
		ban_time = 10,
		fine_amount = 500000,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = nil,
		ban_time = -1,
		fine_amount = nil,
		kick = nil,
	},
}

Config.RDM = {
	{
		resoan = 'Offence 1',
		jail_Time = nil,
		cs_count = 300,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = nil,
		ban_time = -1,
		fine_amount = nil,
		kick = nil,
	},
}	

Config.TRP = {
	{
		resoan = 'Offence 1',
		jail_Time = 30,
		cs_count = nil,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = 80,
		ban_time = nil,
		fine_amount = 50000,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = nil,
		cs_count = 120,
		ban_time = nil,
		fine_amount = 100000,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = 200,
		ban_time = nil,
		fine_amount = 200000,
		kick = nil,
	},
	{
		resoan = 'Offence 5',
		jail_Time = nil,
		cs_count = 250,
		ban_time = 1,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 6',
		jail_Time = nil,
		cs_count = 400,
		ban_time = nil,
		fine_amount = 300000,
		kick = nil,
	},
	{
		resoan = 'Offence 7',
		jail_Time = nil,
		cs_count = 500,
		ban_time = 7,
		fine_amount = nil,
		kick = nil,
	},

}

Config.SEARCH = {
	{
		resoan = 'Warn',
		jail_Time = nil,
		cs_count = nil,
		ban_time = nil,
		fine_amount = 50000,
		kick = nil,
	},
	{
		resoan = 'Offence 1',
		jail_Time = nil,
		cs_count = 60,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = nil,
		cs_count = 80,
		ban_time = nil,
		fine_amount = 50000,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = nil,
		cs_count = 120,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = 200,
		ban_time = nil,
		fine_amount = 50000,
		kick = nil,
	},
	{
		resoan = 'Offence 5',
		jail_Time = nil,
		cs_count = 250,
		ban_time = 1,
		fine_amount = 300000,
		kick = nil,
	},
	{
		resoan = 'Offence 6',
		jail_Time = nil,
		cs_count = 400,
		ban_time = nil,
		fine_amount = 100000,
		kick = nil,
	},
	{
		resoan = 'Offence 7',
		jail_Time = nil,
		cs_count = 500,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},

}
Config.BRP = {
	{
		resoan = 'Warn',
		jail_Time = nil,
		cs_count = nil,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 1',
		jail_Time = nil,
		cs_count = nil,
		ban_time = nil,
		fine_amount = 100000,
		kick = nil,
	},
	{
		resoan = 'Offence 2',
		jail_Time = 30,
		cs_count = nil,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 3',
		jail_Time = 60,
		cs_count = nil,
		ban_time = nil,
		fine_amount = nil,
		kick = nil,
	},
	{
		resoan = 'Offence 4',
		jail_Time = nil,
		cs_count = 100,
		ban_time = nil,
		fine_amount = 150000,
		kick = nil,
	},
	{
		resoan = 'Offence 5',
		jail_Time = nil,
		cs_count = 250,
		ban_time = nil,
		fine_amount = 250000,
		kick = nil,
	},
}